### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by maxhollmann** [Yuki-Inoue/jupyter_on_rails#21]
Hi Yuki,

Thanks for the work on this, super useful. I'd like to use it on a client project, but can't because it doesn't have a license (https://opensource.stackexchange.com/a/1721). Would you mind adding one?

Cheers!

**Comment by Yuki-Inoue** [comment]
Hi, is GPL fine for you?

**Comment by maxhollmann** [comment]
I think so, but I'm not sure actually. LGPL would be fine, so would MIT which is the most common in the ruby community. https://choosealicense.com/ has good information about the different licenses.
