### ISSUE TITLE
.irbrc file not loaded

### ISSUE THREAD

**Issue by elalemanyo** [Yuki-Inoue/jupyter_on_rails#62]
Hi,
I am using a .irbrc file, this file is working when I run a rails console, but not inside a jupyter notebook.
Is this normal?

Thanks

**Comment by Yuki-Inoue** [comment]
irb is an REPL process; iruby, which this jupyter_on_rails gem relies on, is also an REPL process.

> Is this normal?

So no, I assume it is not normal for iruby / this gem to load irbrc.
